name: Build Deploy

on:
  push:
    branches:
      - master

env:
  ACTIONS_RUNNER_DEBUG: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build with maven
        run: |
          chmod +x ./mvnw
          ./mvnw package

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/a13heymartbkbhr:latest

      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: 'a13autehnticate'
          flags: '--allow-unauthenticated'
          image: '${{ secrets.DOCKERHUB_USERNAME }}/a13autehnticate:latest'
          env:
            SPRING_DATABASE_URL=jdbc:postgresql://${{secrets.JDBC_DATABASE_URL}}/authenticate
            SPRING_DATABASE_USERNAME=${{secrets.JDBC_DATABASE_USERNAME}}
            SPRING_DATABASE_PASSWORD=${{secrets.JDBC_DATABASE_PASSWORD}}